language: node_js

node_js:
  - "6.3.1"
  - "7"

sudo: false

branches:
  except:
    - gh-pages

script:
  - npm test --cover

after_script:
  - cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
