check:
  global:
    statements: 80
    functions: 80
    branches: 40
    lines: 40
  each:
    statements: 79
    functions: 50
    branches: 79
    lines: 79
    excludes:
        - lib/bar.js # 40, 0, 40, 0
